### PR TITLE
Improve performance of Redmi 9

### PR DESCRIPTION
**Pull request by ghost**
Helps with application startup time, keeping applications responsive.
Tested by opening and closing applications, switching between recent applications, scrolling within applications and so on.

### CODE REVIEW

**Comment by phhusson** [comment]
I highly doubt this is correct, but I'm downloading galahad firmware for confirmation

**Comment by phhusson** [comment]
No blob in lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys match any of those three properties.

**Comment by ghost** [comment]
Since when did redmi 9 get miui 14?
I use miui 13 from here https://xiaomifirmwareupdater.com/miui/lancelot/stable/V13.0.4.0.SJCMIXM/

Screenshot_20240308_072459

**Comment by phhusson** [comment]
My reference is https://dumps.tadiphone.dev/dumps/redmi/galahad

**Comment by ghost** [comment]
what should I look for from there?
not this one?

https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/aosp-device-tree/proprietary-files.txt?ref_type=heads#L1846

https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/system/system/lib/libmtkperf_client.so?ref_type=heads

https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/system/system/lib64/libmtkperf_client.so?ref_type=heads

https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/vendor/lib/libmtkperf_client_vendor.so?ref_type=heads

https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/vendor/lib64/libmtkperf_client_vendor.so?ref_type=heads

**Comment by ghost** [comment]
maybe I'm wrong.
but I checked on lineageos they also have these properties.

https://github.com/LineageOS/android_device_xiaomi_rosemary/blob/lineage-20/system.prop#L47

https://github.com/LineageOS/android_device_xiaomi_mt6768-common/blob/lineage-20/system.prop#L51

it's time to work, sorry if I can't reply.

**Comment by ghost** [comment]
I flashed with and without "mtk_perf" 3 times and I think it does have effect.

Steps to Reproduce:

- Brightness level 100%.
- On first boot, open all AOSP apps (I find apps load faster)
- Go to the recent screen, scroll left and right (I found it very light and responsive).

I also checked MIUI.

IMG_20240308_133558

**Comment by ghost** [comment]
Hey @phhusson before I close this PR let me ask you something.

Redmi 9 uses power_profile.xml which contains the old configuration which has been deprecated:
**ambient.on**
**screen.on**
**screen.full**

May I change them to:
**ambient.on.display0**
**screen.on.display0**
**screen.full.display0**

Reference: https://android.googlesource.com/platform/frameworks/base/+/8ac63071a4e6%5E%21/

The person who used to make the overlay for Redmi 9 didn't put the power_profile.xml file.
And I checked using `dumpsys overlay` that the power_profile.xml was already read by GSI.
So it makes sense he didn't put it.

If it is allowed to change them I will add a modified power profile.xml to the overlay.

**ambient.on** > **ambient.on.display0**
**screen.on** > **screen.on.display0**
**screen.full** > **screen.full.display0**

**Comment by phhusson** [comment]
Uh yeah you can do that if you want. But the psych you have still has
the legacy compatibility code path, and it's likely we'll keep this
longer than Google.
Thanks for pointing this out

**Comment by ghost** [comment]
@phhusson I just added it [93](https://github.com/TrebleDroid/vendor_hardware_overlay/pull/93)

**Comment by phhusson** [comment]
> what should I look for from there? not this one?
> 
> https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/aosp-device-tree/proprietary-files.txt?ref_type=heads#L1846
> 
> https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/system/system/lib/libmtkperf_client.so?ref_type=heads
> 
> https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/system/system/lib64/libmtkperf_client.so?ref_type=heads

System files are irrelevant since they are not used in GSI

> https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/vendor/lib/libmtkperf_client_vendor.so?ref_type=heads
> 
> https://dumps.tadiphone.dev/dumps/redmi/galahad/-/blob/lancelot-user-12-SP1A.210812.016-V14.0.0.1.SJCCNXM-release-keys/vendor/lib64/libmtkperf_client_vendor.so?ref_type=heads

Those file don't do any reference to the properties you mentioned

**Comment by ghost** [comment]
Thanks for the explanation.

You are right sir @phhusson I don't need this.
In fact I just realized the function of "**Rotation perf hint instead of touch**" after reading the description here:
https://github.com/TrebleDroid/platform_frameworks_base/commit/a501d218943c17e76bb36d09083a133228eaf186

I didn't activate it because the description wasn't clear on Phh Treble Settings it only mentioned "**For Mediatek devices**".

Could you please update the description to something like "**Might makes the device much smoother**".
And **YES!** it actually makes Redmi 9 run smoother.

Thank you for your hard work, you are a genius.

**Pull request closed without merging**
