### PR TITLE
rw-system.sh: SurfaceFlinger tweaks on Redmi 9 [Improves system smoothness & Fix lag on QS panel]

### PR DESCRIPTION
**Pull request by ghost**
Disabling client composition cache improves system smoothness.
Tested.

@phhusson
I changed the previous description which said disabling client composition could also fix lags on the QS panel when media output is displayed, which it does not at all.

### CODE REVIEW

**Comment by ghost** [comment]
I found that disabling display refresh rate override fixed lags when media output is showed on QS panel.
Tested.

Another workaround is `Misc features > Force FPS`.

Ready to merge @phhusson

**Comment by phhusson** [comment]
That properties only change the FPS of the screen. It doesn't change anything related to rendering.
And to debug screen FPS infos, just enable the show display fps option in developer settings

**Comment by phhusson** [comment]
Also please explain what ro.surface_flinger.enable_frame_rate_override actually does, because I couldn't find any documentation about it

**Comment by ghost** [comment]
> That properties only change the FPS of the screen. It doesn't change anything related to rendering. And to debug screen FPS infos, just enable the show display fps option in developer settings

Did you mean `Misc features > Force FPS`?
Yes I know it only changes the FPS of the screen.
And `Show refresh rate` in **Developer options** always shows **60fps**.
That's why I **never** activated it before.

In a state of frustration after hours I searched and tried various properties from here:
https://android.googlesource.com/platform/frameworks/native/+/refs/heads/main/services/surfaceflinger
and https://cs.android.com/ but had no luck.

Then I tried enabling `Misc features > Force FPS`.
And what a surprise the lags when media output is showing on QS panel are gone.

Then I remembered the LineageOS issues some time ago.
https://gitlab.com/LineageOS/issues/android/-/issues/7036
https://gitlab.com/LineageOS/issues/android/-/issues/7121

Which has become a common problem.
https://review.lineageos.org/q/Disable+display+refresh+rate+override

Then I tried `ro.surface_flinger.enable_frame_rate_override`
It turns out that `ro.surface_flinger.enable_frame_rate_override false` managed to fix the lags when media output is showing on QS panel issue.

> Also please explain what ro.surface_flinger.enable_frame_rate_override actually does, because I couldn't find any documentation about it

Why should I explain it when Google itself doesn't?
I just try and see.

**Comment by phhusson** [comment]
> Then I remembered the LineageOS issues some time ago.
> https://gitlab.com/LineageOS/issues/android/-/issues/7036
> https://gitlab.com/LineageOS/issues/android/-/issues/7121

Those say that this changes screen FPS during youtube playback. You didn't mention video playback even once, but claim that it fixes QS lag.

**Comment by ghost** [comment]
> > Then I remembered the LineageOS issues some time ago.
> > https://gitlab.com/LineageOS/issues/android/-/issues/7036
> > https://gitlab.com/LineageOS/issues/android/-/issues/7121
> 
> Those say that this changes screen FPS during youtube playback. You didn't mention video playback even once, but claim that it fixes QS lag.

It's in the commit description.

https://github.com/TrebleDroid/device_phh_treble/pull/64/commits/f21c2f63e12c049206c6656e85d3bdcad136cc20

Fix issues like lags when media output is showed on QS panel

Test:
- Play/stream videos for example in the browser.
- Pull down Quick Settings.
- Scroll left and right on the QS panel. 

By the way, not only the YouTube app, all the videos that I play/stream on other applications make lag in the QS panel.

Edit:
Forgot to mention tested on:
- Youtube (Official YT client).
- Cromite (Chromium based browser).
- NewPipe (YT client).
- InnerTune (YT music client).
- Infinity for Reddit (lag occurs even without media output showing on QS).

**Pull request merged**
