### PR TITLE
Fix UI lags on Redmi 9

### PR DESCRIPTION
**Pull request by ghost**
Add SurfaceFlinger properties from MIUI 13 and from Redmi 9 device tree.

Tested.

### CODE REVIEW

**Comment by phhusson** [comment]
Did you actually check which property does  what, or just blindly copy/pasted a bunch of props?

**Comment by ghost** [comment]
It's from stock FW.
Other than that from here:
https://github.com/mt6768-dev/android_device_xiaomi_mt6768-common/commits/lineage-21/vendor.prop
https://source.android.com/docs/core/graphics/unsignaled-buffer-latch

But really lags is now gone.

**Comment by ghost** [comment]
But really lags is now gone.
I didn't even activate the Misc features in Phh Treble Settings e.g `Mediatek GED KPI support` , `Rotation perf hint instead of touch` and `Disable SF GL backpressure`.

But I can say that now it is smoother and will be even better after activating `Mediatek GED KPI support` , `Rotation perf hint instead of touch` and `Disable SF GL backpressure`.
And `Disable HW overlays` is no longer needed of course.

**Comment by ghost** [comment]
These are all from MIUI.

```
[debug.sf.disable_backpressure]: [1]
[debug.sf.early.app.duration]: [20000000]
[debug.sf.early.sf.duration]: [27600000]
[debug.sf.earlyGl.app.duration]: [20000000]
[debug.sf.earlyGl.sf.duration]: [27600000]
[debug.sf.hwc.min.duration]: [17000000]
[debug.sf.late.app.duration]: [20000000]
[debug.sf.late.sf.duration]: [27600000]
[debug.sf.use_phase_offsets_as_durations]: [1]
[ro.surface_flinger.force_hwc_copy_for_virtual_displays]: [true]
[ro.surface_flinger.max_frame_buffer_acquired_buffers]: [3]
[ro.surface_flinger.primary_display_orientation]: [ORIENTATION_0]
[ro.surface_flinger.supports_background_blur]: [1]
```
the other from
https://github.com/mt6768-dev/android_device_xiaomi_mt6768-common/commits/lineage-21/vendor.prop
https://source.android.com/docs/core/graphics/unsignaled-buffer-latch

**Comment by phhusson** [comment]
That's really not my question.
My question is do you know which prop is useful, which is useless?

**Comment by ghost** [comment]
> That's really not my question. My question is do you know which prop is useful, which is useless?

Sorry, it was in the middle of the night when I made the pull request and I was very sleepy.

This is my explanation:

**A**. (Taken from MIUI)
```
setprop debug.sf.early.app.duration 20000000
setprop debug.sf.earlyGl.app.duration 20000000
setprop debug.sf.earlyGl.sf.duration 27600000
setprop debug.sf.early.sf.duration 27600000
setprop debug.sf.hwc.min.duration 17000000
setprop debug.sf.late.app.duration 20000000
setprop debug.sf.late.sf.duration 27600000
```
Lags without these props (A without B will lags & B without A will lags).

**B**. (Taken from MIUI)
`setprop debug.sf.use_phase_offsets_as_durations 1`
Lags without this prop (A without B will lags & B without A will lags).

**C**. (Taken from Redmi 9 device tree)
`setprop ro.surface_flinger.enable_frame_rate_override false`
This got enabled by default on U, and it causes apps like Chrome and Youtube to set the refresh rate to 30FPS when playing some videos.

**D**. (Taken from MIUI)
```
setprop ro.surface_flinger.force_hwc_copy_for_virtual_displays true
setprop ro.surface_flinger.max_frame_buffer_acquired_buffers 3
setprop ro.surface_flinger.primary_display_orientation ORIENTATION_0
```
AOSP reads these props and appears in getprop.
I can delete them if you think redundant.

**E**. (I added it myself)
`setprop debug.sf.auto_latch_unsignaled 1`
This is enabled by default in Android 13.
I can choose to delete it if you feel it is redundant.

**F**. (Taken from Redmi 9 device tree)
`setprop debug.sf.disable_client_composition_cache 1`
Disabling client composition cache improves system smoothness and fix issues like lags when media output is showed on qs panel

**G**. (Taken from Redmi 9 device tree)
`setprop debug.sf.enable_gl_backpressure 1`
This does not appear in getprop.
But after entering Phh Treble Settings (without making any changes) then it appears in getprop.
So I added this too.
I can choose to delete it if you feel it is redundant.

**H**. (Taken from Redmi 9 device tree)
`setprop debug.sf.enable_transaction_tracing false`
Disable continuous transaction tracing.

**I**. (Taken from Redmi 9 device tree)
`debug.sf.predict_hwc_composition_strategy`
This is enabled by default but honestly it's not clear what it does.

**Comment by ghost** [comment]
I've tested it again and this is the summary

### Usefull

**A** (fix lags)
```
setprop debug.sf.late.sf.duration 27600000
setprop debug.sf.late.app.duration 20000000
setprop debug.sf.early.sf.duration 27600000
setprop debug.sf.early.app.duration 20000000
setprop debug.sf.earlyGl.sf.duration 27600000
setprop debug.sf.earlyGl.app.duration 20000000
setprop debug.sf.hwc.min.duration 17000000
```

**B** (fix lags)
`setprop debug.sf.use_phase_offsets_as_durations 1`

**F** (improves system smoothness)
`setprop debug.sf.disable_client_composition_cache 1`

### Useless
 
**C** (no problem occurred)
`setprop ro.surface_flinger.enable_frame_rate_override false`

**D** (enabled by default)
```
setprop ro.surface_flinger.force_hwc_copy_for_virtual_displays true
setprop ro.surface_flinger.max_frame_buffer_acquired_buffers 3
setprop ro.surface_flinger.primary_display_orientation ORIENTATION_0
```

**E** (let the system choose)
`setprop debug.sf.auto_latch_unsignaled 1`
actually there is `vendor.debug.sf.latch_unsignaled 1` instead of `debug.sf.latch_unsignaled 1` but it doesn't have any effect but rather makes it stutter.
putting `vendor.debug.sf.latch_unsignaled 1` will automatically enable `debug.sf.latch_unsignaled 1`

**G** (will be active if you enter Phh Treble Settings without making any changes).
`setprop debug.sf.enable_gl_backpressure 1`

**H** (no visible effect)
`setprop debug.sf.enable_transaction_tracing false`

**I** (no visible effect)
`debug.sf.predict_hwc_composition_strategy 0`

**Comment by ghost** [comment]
Done @phhusson

**Comment by phhusson** [comment]
Thank you very much

**Pull request merged**
