### PR TITLE
Rewrite lancelot debugging stuff

### PR DESCRIPTION
**Pull request by ghost**
I just realized that for GSI, MIUI 12 (A11) vendor has much better performance compared to MIUI 13 (A12) vendor.
So I decided to retest the existing properties and rewrite them as they are now.

Removed:
`debug.renderengine.backend skiaglthreaded` > causes benchmark score to drop on MIUI 12 vendor.
`debug.sf.predict_hwc_composition_strategy 0` > causes benchmark score to drop on MIUI 12 vendor.
`debug.stagefright.c2inputsurface -1` > causes error when starting screen recording on MIUI 12 vendor.
`media.stagefright.thumbnail.prefer_hw_codecs true` > unclear whether it works or not.

Added:
`resetprop_phh --delete ro.surface_flinger.vsync_event_phase_offset_ns`
`resetprop_phh --delete ro.surface_flinger.vsync_sf_event_phase_offset_ns`
^
From vendor/build.prop on MIUI 12.
Conflicts with SurfaceFlinger durations from MIUI 13.
Need to be removed so that the display is not blank when GSI is installed on top of MIUI 12 vendor.

With this configuration, MIUI 12 vendor scores about 250 points more than MIUI 13 vendor on 3DMARK Sling Shot.
For MIUI 13 vendor, no changes.

I also updated the Redmi 9 presets to complement this.
https://github.com/TrebleDroid/treble_presets/pull/13

### CODE REVIEW

**Comment by ghost** [comment]
Please merge @phhusson @ponces
Thanks.

**Comment by ponces** [comment]
I don't have the needed knowledge to know if this makes sense at all or not.
My only question is: is that "performance increase" really noticeable on your daily usage?
Or are you only caring about (in my opinion) some questionable benchmark results?

Off-topic: please don't tag me on a daily basis to get your PR merged asap...

**Comment by ghost** [comment]
Sorry Ponces for bothering you.

Yes, I see the difference especially the graphics

I think the benchmark scores are reliable.
I once made an issue in your aosp repository about lag on the trebuchet launcher (I have closed it).
It happens when I install GSI on top of MIUI 13 (A12) vendor.
But not when I install GSI on top of MIUI 12 (A11) vendor.
Also it is smoother when browsing and gaming with MIUI 12 (A11) vendor.

MIUI 12 (A11) vendor does not have the non-working audio on calls issue while MIUI 13 (A12) vendor does.
Also the echo issue on MIUI 12 (A11) vendor is not as bad as on MIUI 13 (A12)

The only drawback of MIUI 12 (A11) vendor is the screen recording issue that does not work.
Actually there is a way but it breaks the screen recording function of MIUI 13 (A12) vendor.
So I did not include it in the PR.

**Comment by ghost** [comment]
Also this does not mean that GSI cannot be installed on MIUI 13 vendor after this PR.
instead this PR is to fix the blank display when installed on MIUI 12 vendor.
So we have a choice whether to install GSI on MIUI 13 vendor or MIUI 12 vendor later.

I just got rid of the useless debugging stuff with this situation so that it benefits both (when using MIUI 13 vendor or MIUI 12 vendor).

**Pull request closed without merging**
