### PR TITLE
Fix Samsung Fingerprint detection

### PR DESCRIPTION
**Pull request by Svirusx**
Maybe in /odm/etc/vintf is too manifest.xml too? i don't have this folder in my Samsung.

### CODE REVIEW

**Comment by phhusson** [comment]
Do you have a device on which this is actually an issue?

**Comment by Svirusx** [comment]
With my S20 FE 5G fingerprint works at AOSP. Normally this code mounts
mount -o bind system/phh/empty /system/etc/permissions/android.hardware.fingerprint.xml
for my samsung, looks this isn't issue but. I don't know of it was intentionally.

**Comment by phhusson** [comment]
Yes it is intentional.
Those devices will have /vendor/etc/permissions/android.hardware.fingerprint.xml which takes precedence.

> With my S20 FE 5G fingerprint works at AOSP.

Are you saying that with your change fingerprint works, and without your change it doesn't work?

**Comment by Svirusx** [comment]
When it is intentional than nothing to do here, discarding pull, i through that it might be wrong. Fingerprint work with and without this change so nothing is needed to change.

**Pull request closed without merging**
