### PR TITLE
fix nubia 6 series (6/6pro/6s/6spro) dt2w + fod hbm

### PR DESCRIPTION
**Pull request by boydaihungst**
I modify from F10 key to POWER key of Generic.kl file.
```
// Output from getevent -lp

NX669J:/ # getevent -lp /dev/input/event3
add device 1: /dev/input/event3
  name:     "nubia_goodix_ts"
  events:
    KEY (0001): KEY_F9                KEY_F10               KEY_F11               KEY_F12
                KEY_POWER             BTN_TOOL_FINGER       BTN_TOUCH
    ABS (0003): ABS_X                 : value 854, min 0, max 1080, fuzz 0, flat 0, resolution 0
                ABS_Y                 : value 1448, min 0, max 2400, fuzz 0, flat 0, resolution 0
                ABS_MT_SLOT           : value 0, min 0, max 9, fuzz 0, flat 0, resolution 0
                ABS_MT_TOUCH_MAJOR    : value 0, min 0, max 255, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_X     : value 0, min 0, max 1080, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_Y     : value 0, min 0, max 2400, fuzz 0, flat 0, resolution 0
                ABS_MT_TRACKING_ID    : value 0, min 0, max 65535, fuzz 0, flat 0, resolution 0
  input props:
    INPUT_PROP_DIRECT
```

```
// Output from dumpsys input

    8: nubia_goodix_ts
      Classes: KEYBOARD | TOUCH | TOUCH_MT
      Path: /dev/input/event3
      Enabled: true
      Descriptor: 4055b8a032ccf50ef66dbe2ff99f3b2474e9eab5
      Location: goodix_ts/input0
      ControllerNumber: 0
      UniqueId:
      Identifier: bus=0x0000, vendor=0xbeef, product=0xdead, version=0x28bb, bluetoothAddress=<not set>
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile:
      VideoDevice: <none>
      SysfsDevicePath: /sys/devices/virtual
```

### CODE REVIEW

**Comment by phhusson** [comment]
>  I modify from F10 key to POWER key of Generic.kl file.

Please change to WAKEUP.

It's weird to have such a big kl while you could literally have just the WAKEUP line, but fine.

With regards to the back touchscreen, please rather try this:
`setprop persist.sys.phh.evgrab nubia_sar0_channel0`

Ok for the chmod

**Comment by boydaihungst** [comment]
> > I modify from F10 key to POWER key of Generic.kl file.
> 
> Please change to WAKEUP.
> 
> It's weird to have such a big kl while you could literally have just the WAKEUP line, but fine.
> 
> With regards to the back touchscreen, please rather try this: `setprop persist.sys.phh.evgrab nubia_sar0_channel0`
> 
> Ok for the chmod


That prop doesn't seem to work.  I rebuilt the ROM and it is not working.
Screenshot_20231018-061255_Termux

**Comment by phhusson** [comment]
Do you have the /system/bin/evgrab binary? /system/etc/init/evgrab.rc init script?

**Comment by boydaihungst** [comment]
No. Both are not found.

**Comment by boydaihungst** [comment]
The installed files list doesn't have evgrab, but I noticed "xiaomi-motor" binary file which is in [`cmds/Android.bp`](https://github.com/TrebleDroid/device_phh_treble/blob/83a003a2e19ad10e689b4aba49c85ddc8e71173d/cmds/Android.bp#L116C9-L116C21) as well.  
[installed-files.txt](https://github.com/TrebleDroid/device_phh_treble/files/13032960/installed-files.txt)

**Comment by phhusson** [comment]
Oh great I never actually did the commit to add it... Sorry about that.

Take https://treble.phh.me/evgrab and run it as root after setting the prop. Does it properly "steal" that back touchscreen?

**Comment by boydaihungst** [comment]
Wow. It worked. `getevent` won't show any event from `nubia_sar0_channel0` anymore. So now how to add rc init and evgrab to the new build?

**Comment by phhusson** [comment]
https://github.com/TrebleDroid/device_phh_treble/commit/0adf30305a7a028755ab7bbae84087f5fabec457 (done on android-13.0 and android-14.0 branches)

**Comment by boydaihungst** [comment]
Done. Tested with new build. Everything works as expected. Many thanks.

**Comment by phhusson** [comment]
Merged

**Pull request closed without merging**
