### PR TITLE
Re-enable auto latch & Switch to threaded Skia render engine backend

### PR DESCRIPTION
**Pull request by ghost**
Somehow needed after updating the overlay based on LineageOS.

### CODE REVIEW

**Comment by phhusson** [comment]
What does "needed" mean here? The device won't boot without those changes?

**Comment by phhusson** [comment]
debug.sf.enable_transaction_tracing's default value is already false. Also most ROMs are running as user, and this boolean is simply ignored on user ROMs

**Comment by ghost** [comment]
I have removed debug.sf.enable_transaction_tracing false
I previously checked dumpsys SurfaceFlinger, I saw it was active.
So I thought about disabling it, especially the Official LineageOS also did the same thing.
But yes you know better than me.

Sorry for not providing a clear description.
debug.sf.auto_latch_unsignaled 0 was needed to restore auto latch because somehow the device became a bit heavy after changing the brightness overlay.

Setting debug.renderengine.backend skiaglthreaded regardless placebo or not, I feel the rendering is smoother.

**Comment by ghost** [comment]
Ready to merge @phhusson

**Pull request merged**
