### PR TITLE
brightness fix for platform ums512 And ums9230

### PR DESCRIPTION
**Pull request by Veynamer**
Successful use of GSI with excellent brightness on devices with Unisoc

### CODE REVIEW

**Comment by phhusson** [comment]
How can you be sure they all have it?
I've definitely seen unisoc devices with working backlight control without it.
Though I have no idea what "ums512" and "ums9230" refers to precisely

**Comment by Veynamer** [comment]
Ums512 This Unisoc Т610 And 618, 9230 These are 612, 606 and it seems there is also 616

**Comment by Veynamer** [comment]
I collected reviews on the forum and telegrams and a very large number of smartphone models on these processors had a bug with brightness and this is how it was solved

**Comment by phhusson** [comment]
It doesn't mean that they /all/ have this issue. This commit would break it for them.

Just for reference my SC9863A doesn't have this issue.

Also, why not just use the "use alternate backlight scale" in treble settings? If it isn't reading the value from the correct /sys, I'd rather fix it

**Comment by Veynamer** [comment]
But in any case, it should work, of course I can’t cover almost all devices on these processors, but I did as many as I could. I had to collect information and look at dumps for a month

**Comment by phhusson** [comment]
What did you look for in dumps to come to this conclusion?

**Comment by Veynamer** [comment]
I was looking at the mechanism they use to determine the maximum brightness through the prop value

**Pull request merged**
