### PR TITLE
Galaxy J2 Prime

### PR DESCRIPTION
**Pull request by nhglong**

### CODE REVIEW

**Comment by phhusson** [comment]
> E vndksupport: Could not load /vendor/lib/hw/camera.mt6735.so from default namespace: dlopen failed: file offset for the library "libpdx_default_transport.so" >= file size: 0 >= 0.

I think this issue stems from the fact that you're using SELinux Permissive.  Are you indeed using SELinux permissive? If yes, could you try to see if this issue happen with SELinux enforcing?

**Comment by nhglong** [comment]
Enforcing doesn't boot at all because our selinux is quite broken
but i added check so it'll only for that phone
safe for others

**Comment by phhusson** [comment]
https://github.com/TrebleDroid/device_phh_treble/pull/36/commits/663766180d4efdf56ee053517c38260f6081d17a this commit is a completely no-go.
Can you expand as to why codec2 is unsupported?
WRT libpdx_default_transport, I'd rather have a proper fix, because you're not the first to run SELinux permissive, and won't be the last.

**Comment by nhglong** [comment]
Let me see about codec2 problem
About /
Our ccci blobs hardcorded path to /
it will only work if these folder exists

**Comment by nhglong** [comment]
if i replace /protect_s and (_f) with /vendor/pf (ps) then only nvdata and nvram left
optional i can mount nvdata directly to /data/nvram

**Comment by phhusson** [comment]
you can probably sed /nvdata to /dev/n1 and /nvram to /dev/n2 ? something like that?

**Comment by nhglong** [comment]
i updated it again, removing root folder, libpdx_default_transport and codec2
- About codec2, i think it's not supported because it causes null OMX ( didn't check )
[server] INFO: List of video encoders:
    (none)
[server] INFO: List of audio encoders:
    (none)
- About root folder, there is no reference to /nvram in any vendor blobs ( searched all of them ), but something require nvram folder must be in /

**Comment by phhusson** [comment]
k well you can keep ccodec if that's useful (though really you should be able to add it in your custom vendor).
Did you fix libpdx_default_transport in your vendor? It's likely that simply removing /vendor/lib/libpdx_default_transport.so from your custom vendor is enough to fix the issue actually

**Pull request closed without merging**
