### PR TITLE
td : add offlinecharger support

### PR DESCRIPTION
**Pull request by Iceows**
This pull request allows to use the aosp charger and probably all others on huawei phones. It replaces this commit "Add offline Charge Service" - https://github.com/TrebleDroid/platform_system_core/commit/43f44ff1830e3f9e7a32ec4989aab140d2935b83

I think that it is also necessary to adapt a call to turn off the screen after 3 animations on huawei. At the moment it doesn't do it with the aosp loader. I'll post a commit once I find it

-----------
Properly Thanks to Victor Bo/Ponces for base patches.

Additions
| Use default charger service instead gsicharger
| Capabilities SYS_BOOT to be able to directly boot system | Seclabel before run service
| chown-chmod for Smart Charging
| import vendor charger properties (new)
| add selinux rules (new)

---------

### CODE REVIEW

**Comment by ponces** [comment]
Would this imply the revert of https://github.com/TrebleDroid/platform_system_core/commit/43f44ff1830e3f9e7a32ec4989aab140d2935b83?
Cause I can see a lot of common stuff in `charger.rc`

**Comment by phhusson** [comment]
yes

**Comment by ponces** [comment]
If so and assuming you will adopt @phhusson's suggestions, then looks good to me!

**Comment by Iceows** [comment]
New version, start now service charger with root user to avoid chmod/chown
Add the selinux rules which will allow to use the charger which turns off the screen by lowering the brightness to 0. 
Also also supports changing the color of the leds when the battery is charging

**Comment by Iceows** [comment]
Add now ressources for animation

**Comment by ponces** [comment]
Tested. Looks good to me.

**Comment by ponces** [comment]
Just as a side note: I'm not sure if we should add Pixel charger animation or leave that customization to devs...

**Comment by phhusson** [comment]
> Just as a side note: I'm not sure if we should add Pixel charger animation or leave that customization to devs...

Same. I don't mind having it (I don't really like putting proprietary stuff, but that's fairly small, and I agree not having battery percent is an actual bug), so I'll let you guys who do custom GSIs decide whether they want it or not.

**Comment by Iceows** [comment]
The advantage of putting this commit is that it shows how to do it, however I can provide the one used for unit testing, I'll see what it looks like

**Pull request merged**
